# Generated by Django 5.0.4 on 2024-05-01 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('secondname', models.CharField(max_length=50)),
                ('bdate', models.DateField()),
                ('email', models.CharField()),
                ('photo', models.ImageField(upload_to='')),
                ('registerdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
