# Generated by Django 5.0.4 on 2024-05-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_localuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalUser',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
