# Generated by Django 5.0.4 on 2024-05-08 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_localuser_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bdate', models.DateField()),
                ('email', models.CharField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('registerdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
