# Generated by Django 5.0.4 on 2024-05-11 18:27

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0005_localuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='localuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='localuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='localuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='localuser_groups', to='auth.group', verbose_name='Groups'),
        ),
        migrations.AddField(
            model_name='localuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='localuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='localuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='localuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='localuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='localuser_user_permissions', to='auth.permission', verbose_name='User permissions'),
        ),
        migrations.AlterField(
            model_name='localuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
