# Generated by Django 5.0.4 on 2024-05-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localuser',
            name='bdate',
            field=models.DateField(null=True),
        ),
    ]
